---
- name: Manage AWS VPN and Web Services
  hosts: vpn_servers
  become: yes
  tasks:
    - name: Ensure Nginx is running on port 8080
      community.docker.docker_container:
        name: docker-nginx
        image: nginx:latest
        state: started
        published_ports:
          - "8080:80"
