---
###########################################################
#    AWS EC2 Infrastructure with SSL/TLS                 #
#    WireGuard VPN + Nginx Reverse Proxy + LetsEncrypt   #
###########################################################

- name: AWS EC2 Infrastructure Configuration
  hosts: aws
  become: yes
  gather_facts: yes  
  vars:
    # Configuration
    domain_name: "flaz.duckdns.org"
    admin_email: "oflaherty@gmail.com"
    
    # SECURITY: Pulled from vaulted group_vars/all.yml
    duckdns_token: "{{ vault_duckdns_token }}"
    wireguard_password_hash: "{{ vault_wireguard_password_hash }}"
    
    # Firewall rules
    allowed_ssh_ips:
      - "0.0.0.0/0"
    
  pre_tasks:
    - name: Wait for EC2 to be reachable
      wait_for_connection:
        timeout: 30
      register: ec2_connection
      ignore_errors: yes
    
    - name: End play if EC2 unreachable
      meta: end_host
      when: ec2_connection is failed
  
  tasks:
    # ==========================================
    # System Setup
    # ==========================================
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600
      tags: [system]
    
    - name: Install required packages
      apt:
        name:
          - nginx
          - ufw
          - fail2ban
          - unattended-upgrades
          - certbot
          - python3-certbot-nginx
        state: present
      tags: [system, security]

    - name: Ensure Docker service is running
      systemd:
        name: docker
        state: started
        enabled: yes
      tags: [docker]

    # ==========================================
    # DNS & Networking
    # ==========================================
    - name: "DNS | Update DuckDNS IP"
      uri:
        url: "https://www.duckdns.org/update?domains=flaz&token={{ duckdns_token | trim }}&ip={{ ansible_host }}"
        return_content: yes
      register: duckdns_result
      tags: [dns]

    # ==========================================
    # WireGuard (wg-easy) Configuration
    # ==========================================
    - name: Check if wg-easy is already running
      community.docker.docker_container_info:
        name: wg-easy
      register: wg_info
      tags: [docker, wireguard]

    - name: Ensure WireGuard (wg-easy) is running
      community.docker.docker_container:
        name: wg-easy
        image: ghcr.io/wg-easy/wg-easy:latest
        state: started
        restart_policy: unless-stopped
        capabilities:
          - NET_ADMIN
          - SYS_MODULE
        sysctls:
          net.ipv4.conf.all.src_valid_mark: "1"
          net.ipv4.ip_forward: "1"
        volumes:
          - /etc/wireguard:/etc/wireguard
        ports:
          - "51821:51821/tcp"
          - "51820:51820/udp"
        env:
          WG_HOST: "{{ domain_name }}"
          PASSWORD_HASH: "{{ wireguard_password_hash }}"
          WG_DEFAULT_DNS: "1.1.1.1,1.0.0.1"
      when: not (wg_info.exists and wg_info.container.State.Running)
      tags: [docker, wireguard]

    # ==========================================
    # Nginx Configuration
    # ==========================================
    - name: Check if SSL certificate exists
      stat:
        path: "/etc/letsencrypt/live/{{ domain_name }}/fullchain.pem"
      register: ssl_cert
      tags: [always]
    
    - name: Configure Nginx - HTTP only (for initial cert request)
      copy:
        dest: /etc/nginx/sites-available/default
        content: |
          server {
              listen 80;
              server_name {{ domain_name }};
              location /.well-known/acme-challenge/ {
                  root /var/www/html;
              }
              location / {
                  proxy_pass http://127.0.0.1:51821;
                  proxy_set_header Host $host;
                  proxy_set_header X-Real-IP $remote_addr;
                  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
              }
          }
        mode: '0644'
      when: not ssl_cert.stat.exists
      notify: restart nginx
      tags: [nginx]
    
    - name: Configure Nginx - HTTPS with redirect
      copy:
        dest: /etc/nginx/sites-available/default
        content: |
          server {
              listen 80;
              server_name {{ domain_name }};
              location /.well-known/acme-challenge/ {
                  root /var/www/html;
              }
              location / {
                  return 301 https://$server_name$request_uri;
              }
          }
          server {
              listen 443 ssl http2;
              server_name {{ domain_name }};
              ssl_certificate /etc/letsencrypt/live/{{ domain_name }}/fullchain.pem;
              ssl_certificate_key /etc/letsencrypt/live/{{ domain_name }}/privkey.pem;
              ssl_protocols TLSv1.2 TLSv1.3;
              ssl_ciphers 'ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384';
              ssl_prefer_server_ciphers off;
              add_header Strict-Transport-Security "max-age=63072000" always;
              location / {
                  proxy_pass http://127.0.0.1:51821;
                  proxy_set_header Host $host;
                  proxy_set_header X-Real-IP $remote_addr;
                  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                  proxy_set_header X-Forwarded-Proto $scheme;
              }
          }
        mode: '0644'
      when: ssl_cert.stat.exists
      notify: restart nginx
      tags: [nginx, ssl]

    - name: Ensure Nginx is running
      systemd:
        name: nginx
        state: started
        enabled: yes
      tags: [nginx]

    # ==========================================
    # Firewall & Security
    # ==========================================
    - name: Configure UFW rules
      ufw:
        rule: "{{ item.rule }}"
        port: "{{ item.port }}"
        proto: "{{ item.proto }}"
      loop:
        - { rule: 'limit', port: '22', proto: 'tcp' }
        - { rule: 'allow', port: '80', proto: 'tcp' }
        - { rule: 'allow', port: '443', proto: 'tcp' }
        - { rule: 'allow', port: '51820', proto: 'udp' }
      tags: [firewall]

    - name: Enable UFW
      ufw:
        state: enabled
        policy: deny
      tags: [firewall]

    - name: Ensure fail2ban is running
      systemd:
        name: fail2ban
        state: started
        enabled: yes
      tags: [security]

    # ==========================================
    # Health Checks
    # ==========================================
    - name: Verify WireGuard container status
      command: docker ps --filter name=wg-easy
      register: wg_status
      changed_when: false
      tags: [health, wireguard]
    
    - name: Display Status
      debug:
        msg: "✅ WireGuard is healthy and running"
      when: "'wg-easy' in wg_status.stdout and 'Up' in wg_status.stdout"
      tags: [health, wireguard, always]

  handlers:
    - name: restart nginx
      service:
        name: nginx
        state: restarted

    - name: restart fail2ban
      service:
        name: fail2ban
        state: restarted
