#!/usr/bin/env python3
"""
WhatsApp Commander Bot - Minty Server Control via Twilio
Version 0.7.2 - Integrated EE number and Auto-Heal Dashboard
"""
import subprocess
import os
import logging
import json
from flask import Flask, request
from twilio.twiml.messaging_response import MessagingResponse

logging.basicConfig(
    filename=os.path.expanduser('~/commander_audit.log'),
    level=logging.INFO,
    format='%(asctime)s - %(levelname)s - %(message)s'
)

app = Flask(__name__)

# --- MULTIPLE AUTHORIZED NUMBERS ---
ALLOWED_NUMBERS = [
    os.getenv('ALLOWED_NUMBER', 'whatsapp:+44XXXXXXXXXX'), # Primary Number
    'whatsapp:+447XXXXXXXXX'                              # Your EE Number
]
INVENTORY_PATH = os.path.expanduser('~/ansible/inventory.ini')

@app.route("/webhook", methods=['POST'])
def whatsapp_bot():
    # Trim and lowercase to handle auto-capitalization (e.g. "Fleet" vs "fleet")
    incoming_msg = request.values.get('Body', '').strip()
    incoming_lower = incoming_msg.lower() 
    from_number = request.values.get('From', '')
    
    resp = MessagingResponse()
    msg = resp.message()

    # Security Check against authorized list
    if from_number not in ALLOWED_NUMBERS:
        logging.warning(f"Unauthorized access from {from_number}")
        msg.body("Unauthorized access attempt.")
        return str(resp)

    # 1. Full Fleet Dashboard (v0.7.2)
    if incoming_lower in ['fleet', 'stats', 'dashboard']:
        hosts = ['localhost', 'aws', 'az', 'pi']
        response = "🌍 *Minty Fleet Dashboard*\n"
        
        for host in hosts:
            try:
                # Read localhost directly, SSH to remote hosts
                if host == 'localhost':
                    with open('/tmp/fleet_health.json', 'r') as f:
                        raw = f.read()
                else:
                    # Grab the artifact generated by maintenance.yml v0.21
                    raw = subprocess.check_output(
                        ["ssh", host, "cat /tmp/fleet_health.json"], 
                        timeout=3
                    ).decode()
                
                data = json.loads(raw)
                # Display network, docker status (and 🩹 if healed), and uptime
                response += f"\n{data['net']} *{host.upper()}* {data['docker']}"
                response += f"\n└ ⏱️ {data['uptime']} (at {data['time']})"
            except Exception:
                response += f"\n🔴 *{host.upper()}* ⚠️ (Offline/Unreachable)"
        msg.body(response)

    # 2. Manual Update Trigger
    elif incoming_lower == 'update':
        subprocess.Popen(["sudo", "systemctl", "start", "ansible-pull.service"])
        msg.body("🚀 Update triggered manually!")

    # 3. Fleet-wide Ping
    elif incoming_lower == 'pingall':
        try:
            output = subprocess.check_output(["ansible", "all", "-m", "ping", "-i", INVENTORY_PATH]).decode()
            success_count = output.count('"ping": "pong"')
            total_hosts = output.count('=>')
            status_emoji = "🟢" if success_count == total_hosts else "🟡"
            msg.body(f"{status_emoji} *Fleet Health*\n✅ Online: {success_count}/{total_hosts}")
        except Exception as e:
            msg.body(f"❌ Error: {str(e)}")

    else:
        msg.body("Valid commands: fleet, update, pingall")

    return str(resp)

if __name__ == "__main__":
    app.run(host='0.0.0.0', port=int(os.getenv('PORT', 5000)))
