
# This task upgrades all Flatpaks non-interactively and checks for changes.
- name: Upgrade all flatpaks
  ansible.builtin.command: flatpak update --noninteractive
  register: flatpak_update_output
  changed_when: "'app/' in flatpak_update_output.stdout"
