# -*- coding: utf-8 -*-

###########################################################
#                                                         #
#       Martin O'Flaherty: Updated Ansible Playbook       #
#                       Version 0.02                      #
###########################################################

--- 
- 
  become: true
  gather_facts: yes
  hosts: "*"
  ignore_unreachable: true
  tasks:
    -
      include: update.yml
      name: update apt servers
    - 
      include: aptcleanup.yml
      name: "Remove dependencies that are no longer required."
    -
      include: pip.yml
      name: pip3 updates
    -
      include: python.yml
      name: python updates
    - 
      name: "Check if a reboot is needed on all servers"
      register: reboot_required_file
      stat: "path=/var/run/reboot-required get_md5=no"
    
