# -*- coding: utf-8 -*-

###########################################################
#                                                         #
#       Martin O'Flaherty: Updated Ansible Playbook       #
#                       Version 0.02                      #
###########################################################

--- 
- 
  become: true
  gather_facts: yes
  hosts: "*"
  ignore_unreachable: true
    
  tasks:
    - import_tasks: tasks/update.yml
    - import_tasks: tasks/aptcleanup.yml
    - import_tasks: tasks/pip.yml
    - import_tasks: tasks/python.yml
    - import_tasks: tasks/flatpaks update
    - 
      name: "Check if a reboot is needed on all servers"
      register: reboot_required_file
      stat: "path=/var/run/reboot-required get_md5=no"
