--- 
- 
  become: true
  gather_facts: true
  hosts: "*"
  tasks: 
    - 
      package: 
        name: "*"
        state: latest
      name: "install latest desktop packages"
      when: "ansible_distribution in [\"Debian\", \"Ubuntu\", \"Linux Mint\", \"raspberrypi\", \"Pop!_OS\" ]"
    - 
      include: aptcleanup.yml
    -
      include: debug.yml
