## -*- coding: utf-8 -*-

###########################################################
#                                                         #
#       Martin O'Flaherty: Updated Ansible Playbook       #
#                       Version 0.02                      #
###########################################################

--- 
- 
  become: true
  gather_facts: yes
  hosts: "*"
  ignore_unreachable: true
  tasks:
    - include: update.yml
    - include: aptcleanup.yml
    - include: pip.yml
    - include: python.yml
    - include: flatpaks.yml
    name: "Check if a reboot is needed on all servers"
      register: reboot_required_file
      stat: "path=/var/run/reboot-required get_md5=no"
