## -*- coding: utf-8 -*-

###########################################################
#                                                         #
#       Martin O'Flaherty: Updated Ansible Playbook       #
#                       Version 0.02                      #
###########################################################

--- 
- name: Execute playbook tasks on all hosts
  become: true
  gather_facts: yes
  hosts: all
  ignore_unreachable: true
  tasks:
    - include_tasks: update.yml
    - include_tasks: aptcleanup.yml
    - include_tasks: pip.yml
    - include_tasks: python.yml
    - include_tasks: flatpaks.yml

    - name: Check if a reboot is needed
      stat:
        path: /var/run/reboot-required
      register: reboot_required_file

