---
- hosts: localhost
  connection: local
  become: true

  tasks:
  - name: Install Packages
    package:
      name: 
        - htop
        - opera
        - bitwarden
  - name: Update apt repo and cache
    apt: upgrade=dist force_apt_get=yes


