--- 
- 
  become: true
  gather_facts: true
  hosts: "*"
  tasks: 
    - 
      apt: 
        name: "*"
        state: latest
      name: "install \"Latest desktop packages\""
      when: "ansible_distribution in [\"Debian\", \"Ubuntu\", \"Linux Mint\", \"raspberrypi\", \"Pop!_OS\" ]"
    - 
      include: aptcleanup.yml

