---
- hosts: localhost
  connection: local
  become: true

  tasks:
  - name: Make sure Nano is there
    apt:
      name: nano
      state: latest

  tasks:
   - name: Make sure Pihole is upto date
     apt:
     - name: TASK | pihole -up
       service:
         state: restarted
