---
- hosts: "*"
  become: yes
  tasks:
    - name: Update and upgrade apt packages
      become: true
      apt:
        upgrade: full
        update_cache: yes
       # cache_valid_time: 3600
    - name: install "Latest desktop packages"
      apt:
        name: "*"
        state: latest
    
#    -  name: Remove Armory
#       apt:
#         pkg: armory
#         state: absent
    
