---
## -*- coding: utf-8 -*-
###########################################################
#                                                         #
#       Martin O'Flaherty: Ansible Playbook               #
#                       Version 0.03                      #
###########################################################
- name: Execute playbook tasks on Ubuntu hosts
  become: true
  gather_facts: yes
  hosts: ubuntu
  ignore_unreachable: true
  vars_files:
    - ansible_passwords.yml
  tasks:
    - include_tasks: third-party-software.yml
    - include_tasks: sshfs.yml
    - include_tasks: update.yml
    - include_tasks: aptcleanup.yml
    - include_tasks: python.yml
    - include_tasks: flatpaks.yml
    - include_tasks: pi.yml
    - include_tasks: aws.yml
    - name: Check if a reboot is needed
      stat:
        path: /var/run/reboot-required
      register: reboot_required_file
    - name: Reboot the server if required
      reboot:
      when: reboot_required_file.stat.exists
