###########################################################
#                                                         #
#        Martin O'Flaherty first Ansible Playbook         #
#                                                         #
###########################################################

--- 
- 
  become: true
  gather_facts: true
  hosts: "*"
  tasks: 
    - 
      name: "install latest desktop packages"
      package: 
        name: "*"
        state: latest
      when: "ansible_distribution in [\"ubuntu\"]"
    - 
      include: aptcleanup.yml
    - 
      include: debug.yml
