---
- hosts: localhost
  connection: local
  become: true

  tasks:
  - name: install packages
    package:
      name:
        - htop
        - opera
        - bitwarden
  tasks:
  - name: Make sure Nano is there
    apt:
      name: nano
      state: latest
