---
###########################################################
#        Martin O'Flaherty: Ansible Master Playbook       #
###########################################################
# Version History:
# 0.01 - Initial script
# 0.02 - Added modular task includes
# 0.03 - Integrated Ansible Vault for secrets
# 0.04 - Hardened SSH, added 'Stay Out' banner, and 
#        synced AWS/Tailscale orchestration
# 0.05 - Fixed sshfs.yml import structure
###########################################################

- name: Execute playbook tasks on Ubuntu hosts
  hosts: ubuntu:!localhost  # This tells Ansible "ubuntu group, but definitely not localhost"
  become: yes
  
  # Configuration data is pulled automatically from group_vars/all.yml
  vars_files:
    - ansible_passwords.yml

  tasks:
    # --- SECURITY LAYER ---
    - name: Apply SSH Hardening and Banners
      include_tasks: ssh_harden.yml

    # --- APPLICATION LAYER ---
    - name: Install Third Party Software
      include_tasks: third-party-software.yml

    # --- CONFIGURATION LAYER ---
    - name: Install Python Environment
      include_tasks: python.yml

    - name: Manage Flatpak Packages
      include_tasks: flatpaks.yml

    # --- SYSTEM MAINTENANCE ---
    - name: Run System Updates
      include_tasks: update.yml

    - name: Perform APT Cleanup
      include_tasks: aptcleanup.yml

    - name: Check if a reboot is needed
      stat:
        path: /var/run/reboot-required
      register: reboot_required_file

    - name: Reboot the server if required
      reboot:
      when: reboot_required_file.stat.exists

  handlers:
    # Global handler to restart SSH when config changes
    - name: restart sshd
      service:
        name: ssh
        state: restarted

###########################################################
# TOP LEVEL ORCHESTRATION
###########################################################

# Runs tasks on Raspberry Pi group
- import_playbook: pi.yml

# Runs tasks on AWS group (Now enabled via Tailscale)
- import_playbook: aws.yml

# Configure SSHFS mounts (separate playbook)
- import_playbook: sshfs.yml
