---
###########################################################
#        Martin O'Flaherty: Fleet Maintenance             #
###########################################################
# Version History:
# 0.10 - Consolidated Success Notification for entire fleet
# 0.11 - Added Block/Rescue for intelligent notifications
# 0.12 - Renamed Twilio variables to bypass secret scanner
# 0.13 - Enhanced Error Reporting to prevent "False Down" alerts
# 0.14 - Fixed Fleet Reporting Variable
# 0.15 - Optimized host targeting for stack visibility
# 0.16 - Refactored into maintenance.yml, orchestrated by mastersite.yml
# 0.17 - Added check_mode safeguards to prevent WhatsApp spam during dry runs
###########################################################

- name: System Maintenance and Updates
  hosts: all
  become: yes
  
  vars_files:
    - group_vars/all.yml

  tasks:
    - name: Main Fleet Update Block
      block:
        # --- INFRASTRUCTURE & MAINTENANCE ---
        - name: Apply SSH Hardening and Banners
          include_tasks: ssh_harden.yml
          when: inventory_hostname != 'az'

        - name: Manage Azure WireGuard VPN
          include_tasks: azure_vpn_maintenance.yml

        - name: Install Third Party Software
          include_tasks: third-party-software.yml

        - name: Install Python Environment
          include_tasks: python.yml

        - name: Manage Flatpak Packages
          include_tasks: flatpaks.yml

        - name: Run System Updates
          include_tasks: update.yml

        - name: Perform APT Cleanup
          include_tasks: aptcleanup.yml

        - name: Check for Reboot
          stat:
            path: /var/run/reboot-required
          register: reboot_required_file

        - name: Reboot if required
          reboot:
            msg: "Rebooting for system updates"
            reboot_timeout: 3600
          when: reboot_required_file.stat.exists

      rescue:
        # --- ENHANCED FAILURE NOTIFICATION ---
        # This triggers per-host so you know exactly which server failed and why
        - name: Send Failure WhatsApp
          community.general.twilio:
            account_sid: "{{ twilio_sid }}"
            auth_token: "{{ tw_auth_k }}"
            from_number: "whatsapp:{{ twilio_from_number }}"
            to_number: "whatsapp:{{ my_mobile_number }}"
            msg: |
              🚨 *Ansible Fleet ALERT*
              🖥️ *Host:* {{ inventory_hostname }}
              ❌ *Status:* FAILED
              🛠️ *Failed Task:* {{ ansible_failed_task.name }}
              📖 *Error Detail:* {{ ansible_failed_result.msg | default('No message available') | truncate(100) }}
              ⚠️ Server is likely UP but maintenance failed.
          delegate_to: localhost
          when: not ansible_check_mode

    # --- SINGLE FLEET SUCCESS REPORT ---
    # This runs once at the very end of the play after all hosts are processed
    - name: Send Consolidated Success WhatsApp
      community.general.twilio:
        account_sid: "{{ twilio_sid }}"
        auth_token: "{{ tw_auth_k }}"
        from_number: "whatsapp:{{ twilio_from_number }}"
        to_number: "whatsapp:{{ my_mobile_number }}"
        msg: |
          🎬 *Ansible Fleet Update Complete*
          ✅ *Status:* Smooth as butter.
          🖥️ *Updated Stack:* {{ ansible_play_hosts_all | join(', ') }}
          📋 *Version:* 0.17 maintenance module
      delegate_to: localhost
      run_once: true
      when: not ansible_check_mode

  handlers:
    - name: restart sshd
      service:
        name: ssh
        state: restarted
