---
- name: Execute playbook tasks on Pi hosts
  hosts: pi
  become: yes  # <--- THIS IS MISSING
  ignore_unreachable: true
  vars_files:
    - ansible_passwords.yml
  tasks:
    - include_tasks: update.yml
    - include_tasks: aptcleanup.yml
    - include_tasks: python.yml
    # ... rest of your tasks
