- name: Execute playbook tasks on Pi hosts
  hosts: pi
  ignore_unreachable: true
  vars_files:
    - ansible_passwords.yml
  tasks:
    - include_tasks: update.yml
    - include_tasks: aptcleanup.yml
    - include_tasks: python.yml

    - name: Check if a reboot is needed
      stat:
        path: /var/run/reboot-required
      register: reboot_required_file

    - name: Reboot the server if required
      reboot:
      when: reboot_required_file.stat.exists
