---
- name: Manage WireGuard Clients via wg-easy
  hosts: aws
  become: yes

  vars:
    wg_easy_container: "wg-easy"
    local_download_dir: "~/wireguard-clients"
    # We found the files in this closet earlier!
    wg_easy_volume: "/etc/wireguard" 
    wg_easy_port: "51821"
    aws_public_ip: "{{ ansible_host }}"

  tasks:
    - name: Ensure local download directory exists
      file:
        path: "{{ local_download_dir }}"
        state: directory
        mode: '0700'
      delegate_to: localhost
      become: no

    - name: Check if wg-easy container is running
      docker_container_info:
        name: "{{ wg_easy_container }}"
      register: wg_easy_info

    - name: Backup wg-easy configuration (JSON)
      copy:
        # Changed this to look for the .json file we found!
        src: "{{ wg_easy_volume }}/wg0.json"
        dest: "/tmp/wg-easy-backup-{{ ansible_date_time.date }}.json"
        remote_src: yes
        mode: '0600'

    - name: Fetch JSON backup to local machine
      fetch:
        src: "/tmp/wg-easy-backup-{{ ansible_date_time.date }}.json"
        dest: "{{ local_download_dir }}/wg-easy-backup-{{ ansible_date_time.date }}.json"
        flat: yes

    - name: Create instructions file
      copy:
        content: |
          WireGuard (wg-easy) Management Guide
          Backups: {{ local_download_dir }}
          Manage at: http://{{ aws_public_ip }}:{{ wg_easy_port }}
        dest: "{{ local_download_dir }}/WIREGUARD-GUIDE.txt"
      delegate_to: localhost
      become: no

- name: Optional - Deploy WireGuard client to localhost
  hosts: localhost
  connection: local
  become: yes

  vars:
    deploy_client_name: "Linuxmint"
    client_config_source: "~/wireguard-clients/{{ deploy_client_name }}.conf"

  tasks:
    - name: Install WireGuard
      apt:
        name: [wireguard, wireguard-tools, resolvconf, openresolv]
        state: present
      when: deploy_client_name != ""

    - name: Deploy client configuration
      copy:
        src: "{{ client_config_source }}"
        dest: "/etc/wireguard/{{ deploy_client_name }}.conf"
        mode: '0600'
      when: deploy_client_name != ""
