---
###########################################################
#        Martin O'Flaherty: WireGuard Management          #
###########################################################
# Version History:
# 0.1 - 0.3: Initial backup and status verification
# 0.4 - Added active data-path health check (ping test)
###########################################################

- name: Manage WireGuard Clients via wg-easy
  hosts: aws
  become: yes

  vars:
    wg_easy_container: "wg-easy"
    local_download_dir: "~/wireguard-clients"
    wg_easy_volume: "/etc/wireguard" 
    wg_easy_port: "51821"
    aws_public_ip: "{{ ansible_host }}"

  tasks:
    # ... [Previous tasks: backup and container check] ...

    - name: 7. Verify WireGuard is actually running
      command: docker exec {{ wg_easy_container }} wg show
      register: wg_status
      changed_when: false

    - name: 8. Active Tunnel Check (Ping through VPN)
      # This confirms the tunnel isn't just 'up' but is actually routing traffic.
      # We ping the internal gateway address standard for wg-easy (10.8.0.1).
      command: docker exec {{ wg_easy_container }} ping -c 3 10.8.0.1
      register: vpn_ping_test
      ignore_errors: yes
      changed_when: false

    - name: 9. Set Health Fact
      set_fact:
        vpn_health: "{{ '🟢 Healthy' if vpn_ping_test.rc == 0 else '🔴 Routing Failure' }}"

    - name: 10. Report Integrated Health Status
      debug:
        msg: 
          - "VPN Health: {{ vpn_health }}"
          - "Peers Connected: {{ wg_status.stdout_lines | length - 1 }}"

    - name: 11. Create instructions file
      copy:
        content: |
          WireGuard (wg-easy) Management Guide
          Status: {{ vpn_health }}
          Backups: {{ local_download_dir }}
          Manage at: http://{{ aws_public_ip }}:{{ wg_easy_port }}
        dest: "{{ local_download_dir }}/WIREGUARD-GUIDE.txt"
      delegate_to: localhost
      become: no

    # ... [Remaining cleanup tasks] ...
