- name: install cron job (ansible-pull)
  cron:
    user: ansible
    name: "ansible provision"
    minute: "*10"
    job: "/usr/bin/ansible-pull -o -U https://github.com/L0NDONER/ansible_desktop.git > /dev/null"
